// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/35d98e9ef47d52d426d45fadd8b064ed35cc2df7/angular-file-saver/index.d.ts
declare namespace angular {
    /**
     * A core Angular factory proving FileSaver functionality.
     */
    interface FileSaver {
        /**
         * Immediately starts saving a file
         * @param data: a Blob instance;
         * @param filename: a String custom filename (an extension is optional);
         * @param disableAutoBOM : (optional) Boolean Disable automatically provided Unicode text encoding hints;
         */
        saveAs(blob: Blob, fileName: string, disableBOM?: boolean): void;
    }
}
